### ISSUE TITLE
200 files per folder limit

### ISSUE THREAD

**Issue by xob0t** [Luan7805/Onedrive-clenup-versions#1]
thanks for the script, really helped me out, however, there is an annoying 200 files per folder limit, the script ignores anything in a folder after 200 nth file

**Comment by Luan7805** [comment]
You are correct, I was only getting the first page of the API (which contains the first 200 files).

Please test the fix in the branch [Bug-API-Pagination](https://github.com/Luan7805/Onedrive-clenup-versions/tree/Bug-API-Pagination)

**Comment by xob0t** [comment]
thanks for the quick fix, works great!
